baseURL: https://googlecloudplatform.github.io/genai-for-developers
languageCode: en-us
defaultContentLanguage: "en"
title: GenAI For Dev
theme: "genai-for-dev"
enableEmoji: true
disableKinds:
  - "taxonomy"
  - "taxonomyTerm"

  
