# AI enabled code reviews using devai
# - Requires GCP service account stored in GOOGLE_API_CREDENTIALS secret
name: GenAI For Developers
run-name: Reviewing ${{ github.actor }}'s code changes  🚀
on: [push]
env:
  LOCATION: us-central1
  PROJECT_ID: genai-cicd
jobs:
  DevAI-Reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'
      - run: pip install google-cloud-aiplatform
      - run: pip install -i https://test.pypi.org/simple/ devai


      - name: Authorize. with GCP 
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_API_CREDENTIALS }}' 
          project_id: genai-cicd
      - name: Code Review
        run: echo '## Code Review Results 🚀' >> $GITHUB_STEP_SUMMARY
      - run: echo "$(devai review code -c ${{ github.workspace }}/sample-app/src/main/java/anthos/samples/bankofanthos/balancereader)" >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Performance Review
        run: echo '## Performance Review Results 🚀' >> $GITHUB_STEP_SUMMARY
      - run: echo "$(devai review performance -c ${{ github.workspace }}/sample-app/src/main/java/anthos/samples/bankofanthos/balancereader)" >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Security Review
        run: echo '## Security Review Results 🚀' >> $GITHUB_STEP_SUMMARY
      - run: echo "$(devai review security -c ${{ github.workspace }}/sample-app/src/main/java/anthos/samples/bankofanthos/balancereader)" >> $GITHUB_STEP_SUMMARY
        shell: bash